# Generated by Django 4.0.1 on 2022-01-26 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('seats', models.CharField(choices=[('1', 'VIP'), ('2', 'BUSSINESS'), ('3', 'ECONOMY')], default='2', max_length=9)),
                ('num_plate', models.CharField(blank=True, max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('pickup_point', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BusModel',
        ),
        migrations.AddField(
            model_name='bus',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
