# Generated by Django 4.0.1 on 2022-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bussiness_price',
            new_name='business_price',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='bussiness_seats',
            new_name='business_seats',
        ),
        migrations.AlterField(
            model_name='bus',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
