# Generated by Django 4.0.1 on 2022-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bus_route_delete_busmodel_bus_route_id_bus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bussiness_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='bussiness_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='economy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='economy_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='vip_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='vip_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
