# Generated by Django 4.0.1 on 2022-01-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bus_bussiness_price_bus_bussiness_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
    ]
