# Generated by Django 4.0.1 on 2022-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_bussiness_price_bus_business_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='schedule',
            field=models.CharField(max_length=100),
        ),
    ]
