# Generated by Django 4.0.1 on 2022-01-26 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_busmodel_first_class_busmodel_regular_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
