# Generated by Django 4.0.1 on 2022-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_bus_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
