# Generated by Django 4.0.1 on 2022-01-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_bus_route_id_bus_destination_bus_pickup_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='pickup_point',
        ),
        migrations.AddField(
            model_name='bus',
            name='route_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.route'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
