# Generated by Django 4.0.1 on 2022-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=25)),
                ('image', models.ImageField(default='bus.jpg', upload_to='bus_pics')),
                        ],
                ),
    ]
