# Generated by Django 4.0.1 on 2022-01-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_name'),
        ('Basi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.IntegerField(default=1)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bus')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.route')),
            ],
        ),
    ]
